10 Countries:
1. China
2. Japan
3. Sweden
4. Russia
5. Argentina
6. Ukraine
7. Netherlands
8. Spain
9. Denmark
10. Germany

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
#title = % Population Over 65
O65P = pd.DataFrame()
O65P['Country Name'] = ['China', 'Japan', 'Sweden', 'Russia', 'Argentina', 'Ukraine', 'Netherlands', 'Spain', 'Denmark', 'Germany']
O65P['%'] = [10.6, 27, 19.9, 14.2, 11.2, 16.5, 18.8, 19.4, 19.7, 21.5]
O65P

Country Name     %
0        China  10.6
1        Japan  27.0
2       Sweden  19.9
3       Russia  14.2
4    Argentina  11.2
5      Ukraine  16.5
6  Netherlands  18.8
7        Spain  19.4
8      Denmark  19.7
9      Germany  21.5

In [3]:
Data = pd.read_excel('API_SH.MED.BEDS.ZS_DS2_en_excel_v2_1495658.xls')

In [4]:
Columns = Data.loc[Data['Data Source'] == 'Country Name'].values
newArr = Columns.reshape(65)
List = newArr.tolist()
List

['Country Name',
 'Country Code',
 'Indicator Name',
 'Indicator Code',
 1960.0,
 1961.0,
 1962.0,
 1963.0,
 1964.0,
 1965.0,
 1966.0,
 1967.0,
 1968.0,
 1969.0,
 1970.0,
 1971.0,
 1972.0,
 1973.0,
 1974.0,
 1975.0,
 1976.0,
 1977.0,
 1978.0,
 1979.0,
 1980.0,
 1981.0,
 1982.0,
 1983.0,
 1984.0,
 1985.0,
 1986.0,
 1987.0,
 1988.0,
 1989.0,
 1990.0,
 1991.0,
 1992.0,
 1993.0,
 1994.0,
 1995.0,
 1996.0,
 1997.0,
 1998.0,
 1999.0,
 2000.0,
 2001.0,
 2002.0,
 2003.0,
 2004.0,
 2005.0,
 2006.0,
 2007.0,
 2008.0,
 2009.0,
 2010.0,
 2011.0,
 2012.0,
 2013.0,
 2014.0,
 2015.0,
 2016.0,
 2017.0,
 2018.0,
 2019.0,
 2020.0]

In [5]:
Data.columns = List

In [6]:
Data

Country Name         Country Code                    Indicator Name  \
0    Last Updated Date  2020-10-13 00:00:00                               NaN   
1                  NaN                  NaN                               NaN   
2         Country Name         Country Code                    Indicator Name   
3                Aruba                  ABW  Hospital beds (per 1,000 people)   
4          Afghanistan                  AFG  Hospital beds (per 1,000 people)   
..                 ...                  ...                               ...   
262             Kosovo                  XKX  Hospital beds (per 1,000 people)   
263        Yemen, Rep.                  YEM  Hospital beds (per 1,000 people)   
264       South Africa                  ZAF  Hospital beds (per 1,000 people)   
265             Zambia                  ZMB  Hospital beds (per 1,000 people)   
266           Zimbabwe                  ZWE  Hospital beds (per 1,000 people)   

     Indicator Code       1960.0  1961.0  1962.0  1963.0  1964.0  1965.0  ...  \
0               NaN          NaN     NaN     NaN     NaN     NaN     NaN  ...   
1               NaN          NaN     NaN     NaN     NaN     NaN     NaN  ...   
2    Indicator Code  1960.000000  1961.0  1962.0  1963.0  1964.0  1965.0  ...   
3    SH.MED.BEDS.ZS          NaN     NaN     NaN     NaN     NaN     NaN  ...   
4    SH.MED.BEDS.ZS     0.170627     NaN     NaN     NaN     NaN     NaN  ...   
..              ...          ...     ...     ...     ...     ...     ...  ...   
262  SH.MED.BEDS.ZS          NaN     NaN     NaN     NaN     NaN     NaN  ...   
263  SH.MED.BEDS.ZS     0.454545     NaN     NaN     NaN     NaN     NaN  ...   
264  SH.MED.BEDS.ZS          NaN     NaN     NaN     NaN     NaN     NaN  ...   
265  SH.MED.BEDS.ZS     2.801656     NaN     NaN     NaN     NaN     NaN  ...   
266  SH.MED.BEDS.ZS     3.876646     NaN     NaN     NaN     NaN     NaN  ...   

     2011.0  2012.0  2013.0  2014.0  2015.0  2016.0  2017.0  2018.0  2019.0  \
0       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
1       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2    2011.0  2012.0  2013.0  2014.0  2015.0  2016.0  2017.0  2018.0  2019.0   
3       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4       0.4     0.5     0.5     0.5     0.5     NaN     NaN     NaN     NaN   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
262     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
263     0.7     0.7     0.7     0.7     NaN     NaN     NaN     NaN     NaN   
264     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
265     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
266     1.7     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

     2020.0  
0       NaN  
1       NaN  
2    2020.0  
3       NaN  
4       NaN  
..      ...  
262     NaN  
263     NaN  
264     NaN  
265     NaN  
266     NaN  

[267 rows x 65 columns]

In [7]:
Data = Data.drop([0,1,2])
Data

Country Name Country Code                    Indicator Name  \
3           Aruba          ABW  Hospital beds (per 1,000 people)   
4     Afghanistan          AFG  Hospital beds (per 1,000 people)   
5          Angola          AGO  Hospital beds (per 1,000 people)   
6         Albania          ALB  Hospital beds (per 1,000 people)   
7         Andorra          AND  Hospital beds (per 1,000 people)   
..            ...          ...                               ...   
262        Kosovo          XKX  Hospital beds (per 1,000 people)   
263   Yemen, Rep.          YEM  Hospital beds (per 1,000 people)   
264  South Africa          ZAF  Hospital beds (per 1,000 people)   
265        Zambia          ZMB  Hospital beds (per 1,000 people)   
266      Zimbabwe          ZWE  Hospital beds (per 1,000 people)   

     Indicator Code    1960.0  1961.0  1962.0  1963.0  1964.0  1965.0  ...  \
3    SH.MED.BEDS.ZS       NaN     NaN     NaN     NaN     NaN     NaN  ...   
4    SH.MED.BEDS.ZS  0.170627     NaN     NaN     NaN     NaN     NaN  ...   
5    SH.MED.BEDS.ZS  2.061462     NaN     NaN     NaN     NaN     NaN  ...   
6    SH.MED.BEDS.ZS  5.102676     NaN     NaN     NaN     NaN     NaN  ...   
7    SH.MED.BEDS.ZS       NaN     NaN     NaN     NaN     NaN     NaN  ...   
..              ...       ...     ...     ...     ...     ...     ...  ...   
262  SH.MED.BEDS.ZS       NaN     NaN     NaN     NaN     NaN     NaN  ...   
263  SH.MED.BEDS.ZS  0.454545     NaN     NaN     NaN     NaN     NaN  ...   
264  SH.MED.BEDS.ZS       NaN     NaN     NaN     NaN     NaN     NaN  ...   
265  SH.MED.BEDS.ZS  2.801656     NaN     NaN     NaN     NaN     NaN  ...   
266  SH.MED.BEDS.ZS  3.876646     NaN     NaN     NaN     NaN     NaN  ...   

     2011.0  2012.0  2013.0  2014.0  2015.0  2016.0  2017.0  2018.0  2019.0  \
3       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4       0.4     0.5     0.5     0.5     0.5     NaN     NaN     NaN     NaN   
5       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
6       2.6     2.9     2.9     NaN     NaN     NaN     NaN     NaN     NaN   
7       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
262     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
263     0.7     0.7     0.7     0.7     NaN     NaN     NaN     NaN     NaN   
264     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
265     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
266     1.7     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

     2020.0  
3       NaN  
4       NaN  
5       NaN  
6       NaN  
7       NaN  
..      ...  
262     NaN  
263     NaN  
264     NaN  
265     NaN  
266     NaN  

[264 rows x 65 columns]

In [8]:
Data = Data.reset_index(drop = True)

In [9]:
Data.columns

Index([  'Country Name',   'Country Code', 'Indicator Name', 'Indicator Code',
                 1960.0,           1961.0,           1962.0,           1963.0,
                 1964.0,           1965.0,           1966.0,           1967.0,
                 1968.0,           1969.0,           1970.0,           1971.0,
                 1972.0,           1973.0,           1974.0,           1975.0,
                 1976.0,           1977.0,           1978.0,           1979.0,
                 1980.0,           1981.0,           1982.0,           1983.0,
                 1984.0,           1985.0,           1986.0,           1987.0,
                 1988.0,           1989.0,           1990.0,           1991.0,
                 1992.0,           1993.0,           1994.0,           1995.0,
                 1996.0,           1997.0,           1998.0,           1999.0,
                 2000.0,           2001.0,           2002.0,           2003.0,
                 2004.0,           2005.0,          

In [10]:
df = pd.DataFrame()
China = Data.loc[Data['Country Name'] == 'China']
Japan = Data.loc[Data['Country Name'] == 'Japan']
Sweden = Data.loc[Data['Country Name'] == 'Sweden']
Russia = Data.loc[Data['Country Name'] == 'Russian Federation']
Argentina = Data.loc[Data['Country Name'] == 'Argentina']
Ukraine = Data.loc[Data['Country Name'] == 'Ukraine']
Netherlands = Data.loc[Data['Country Name'] == 'Netherlands']
Spain = Data.loc[Data['Country Name'] == 'Spain']
Denmark = Data.loc[Data['Country Name'] == 'Denmark']
Germany = Data.loc[Data['Country Name'] == 'Germany']
df = df.append(China)
df = df.append(Japan)
df = df.append(Sweden)
df = df.append(Russia)
df = df.append(Argentina)
df = df.append(Ukraine)
df = df.append(Netherlands)
df = df.append(Spain)
df = df.append(Denmark)
df = df.append(Germany)
df

Country Name Country Code                    Indicator Name  \
38                China          CHN  Hospital beds (per 1,000 people)   
117               Japan          JPN  Hospital beds (per 1,000 people)   
221              Sweden          SWE  Hospital beds (per 1,000 people)   
200  Russian Federation          RUS  Hospital beds (per 1,000 people)   
7             Argentina          ARG  Hospital beds (per 1,000 people)   
246             Ukraine          UKR  Hospital beds (per 1,000 people)   
174         Netherlands          NLD  Hospital beds (per 1,000 people)   
68                Spain          ESP  Hospital beds (per 1,000 people)   
56              Denmark          DNK  Hospital beds (per 1,000 people)   
53              Germany          DEU  Hospital beds (per 1,000 people)   

     Indicator Code     1960.0  1961.0  1962.0  1963.0  1964.0  1965.0  ...  \
38   SH.MED.BEDS.ZS        NaN     NaN     NaN     NaN     NaN    1.44  ...   
117  SH.MED.BEDS.ZS   9.000000     NaN     NaN     NaN     NaN     NaN  ...   
221  SH.MED.BEDS.ZS  14.200000     NaN     NaN     NaN     NaN     NaN  ...   
200  SH.MED.BEDS.ZS        NaN     NaN     NaN     NaN     NaN     NaN  ...   
7    SH.MED.BEDS.ZS   6.352251     NaN     NaN     NaN     NaN     NaN  ...   
246  SH.MED.BEDS.ZS        NaN     NaN     NaN     NaN     NaN     NaN  ...   
174  SH.MED.BEDS.ZS        NaN     NaN     NaN     NaN     NaN     NaN  ...   
68   SH.MED.BEDS.ZS        NaN     NaN     NaN     NaN     NaN     NaN  ...   
56   SH.MED.BEDS.ZS        NaN     NaN     NaN     NaN     NaN     NaN  ...   
53   SH.MED.BEDS.ZS  10.500000     NaN     NaN     NaN     NaN     NaN  ...   

     2011.0  2012.0  2013.0  2014.0  2015.0  2016.0  2017.0  2018.0  2019.0  \
38      3.8     4.2     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
117     NaN    13.4     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
221     2.7     2.6     2.6     NaN     NaN     NaN     NaN     NaN     NaN   
200     8.6     8.4     8.2     NaN     NaN     NaN     NaN     NaN     NaN   
7       4.5     4.7     4.9     5.0     NaN     NaN     NaN     NaN     NaN   
246     9.0     8.9     8.8     NaN     NaN     NaN     NaN     NaN     NaN   
174     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
68      3.1     3.0     3.0     NaN     NaN     NaN     NaN     NaN     NaN   
56      3.1     NaN     3.1     NaN     2.5     NaN     NaN     NaN     NaN   
53      8.2     8.2     8.3     NaN     NaN     NaN     NaN     NaN     NaN   

     2020.0  
38      NaN  
117     NaN  
221     NaN  
200     NaN  
7       NaN  
246     NaN  
174     NaN  
68      NaN  
56      NaN  
53      NaN  

[10 rows x 65 columns]

In [11]:
beds = pd.DataFrame()

In [12]:
beds['Country Name'] = df['Country Name']

In [13]:
noBed = [4.2, 13.4, 2.6, 8.2, 5, 8.8, 4.7, 3, 2.5, 8.3]

In [14]:
beds['beds1k'] = noBed
beds = beds.reset_index(drop = True)

In [15]:
case = pd.DataFrame()
case['Country Names'] = beds['Country Name']
response = [0.34, 1.36, 58.26, 17.91, 64.94, 14.71, 41.25, 74.38, 12.11, 12.13]
case['Death/100kPop'] = response
case

Country Names  Death/100kPop
0               China           0.34
1               Japan           1.36
2              Sweden          58.26
3  Russian Federation          17.91
4           Argentina          64.94
5             Ukraine          14.71
6         Netherlands          41.25
7               Spain          74.38
8             Denmark          12.11
9             Germany          12.13

In [16]:
features = pd.DataFrame()
features['Country Names'] = O65P['Country Name']
features['beds1k'] = beds['beds1k']
features['%Over65'] = O65P['%']
features['Death/100kPop'] = case['Death/100kPop']
features

Country Names  beds1k  %Over65  Death/100kPop
0         China     4.2     10.6           0.34
1         Japan    13.4     27.0           1.36
2        Sweden     2.6     19.9          58.26
3        Russia     8.2     14.2          17.91
4     Argentina     5.0     11.2          64.94
5       Ukraine     8.8     16.5          14.71
6   Netherlands     4.7     18.8          41.25
7         Spain     3.0     19.4          74.38
8       Denmark     2.5     19.7          12.11
9       Germany     8.3     21.5          12.13

USA response rate aka Death/100kPop = 68.84

In [17]:
target = pd.DataFrame()
target['response'] = features['Death/100kPop']

In [18]:
X = features[['beds1k', '%Over65']]
y = target['response']

In [19]:
reg = LinearRegression().fit(X,y)
reg.score(X,y)

0.3179821673226729

In [20]:
reg.coef_

array([-4.69042678,  0.58105536])

In [21]:
reg.intercept_

47.82062077488726

In [22]:
pred = reg.predict(X)
print(pred)

[34.28001508  0.65739655 47.18851276 17.61010724 30.87630687 16.13227849
 36.69945562 45.02181437 47.54134436 21.38276867]


In [23]:
reg.predict(np.array([[5, 11.2]]))

array([30.87630687])

In [24]:
Usa = pd.DataFrame()
Usa['Country Names'] = ['USA']
Usa['beds1k'] = [2.9]
Usa['%Over65'] = [15.4]
Usa['Death/100kPop'] = [68.84]
Usa

Country Names  beds1k  %Over65  Death/100kPop
0           USA     2.9     15.4          68.84

In [25]:
reg.predict(np.array([[2.9, 15.4]]))

array([43.16663561])